### ISSUE TITLE
Modrinth links lead to "modrinth.com/project/<slug>" resulting in a 404

### ISSUE THREAD

**Issue by intergrav** [devBoi76/modrinthify#1]
The title :p 

Modrinth links go to `/project/[slug]` instead of `/mod,resourcepack,etc/[slug]`

Here is an example:

![image](https://user-images.githubusercontent.com/42325132/202361351-ebd88cd3-256e-43d5-924a-77c2fc3cd242.png)

![image](https://user-images.githubusercontent.com/42325132/202361377-ac7b3df9-d396-484b-b7fa-9c0b4eb25a41.png)

![image](https://user-images.githubusercontent.com/42325132/202361399-345558ba-0085-4ed4-861a-38cfb70d2671.png)

**Comment by devBoi76** [comment]
Thanks for reporting, this turned out to be a really simple fix. The updated version should roll out on firefox and userscript soon, although expect a delay on chrome web store (as usual)

**Comment by intergrav** [comment]
Thanks!
