### ISSUE TITLE
Extension is broken since the modrinth notification update

### ISSUE THREAD

**Issue by TheBossMagnus** [devBoi76/modrinthify#8]
- Mod name got replaced by mod id and 
- Notifications don't get cleared on the Extension
- Broken link (Fixed in #7) 
- Scooped tokens should be recommended and instruction to get them should be updated
- Maybe something else I didn't yet notice

**Comment by devBoi76** [comment]
Thanks, I merged the PR, the mod ID is fixed and I'll make proper clearing of the new notification type next (it will actually remove the notification).

**Comment by devBoi76** [comment]
Notification clearing now works properly, API token information got updated, I think that's everything that broke since the update. I didn't notice any more bugs while testing the new features so I'll close this issue 👍
