### ISSUE TITLE
suggestion: add sinytra connector button

### ISSUE THREAD

**Issue by Moonyol** [devBoi76/modrinthify#9]
![image](https://github.com/devBoi76/modrinthify/assets/92951072/e5c771d1-c6f8-4a98-a5b0-612e2de6cf07)
add a button like this but for [sinytra connector](https://modrinth.com/mod/connector)

**Comment by devBoi76** [comment]
What do you mean? The redirect shows up correctly for this mod
![image](https://github.com/devBoi76/modrinthify/assets/77896685/229e6863-5718-49d0-ac67-1f14bfd0b4ad)
